class Pawn:
    #BLACK OR WHITE
    #MOVE FORWARD 2, MOVE FORWARD 1
    #EN PASSANT

class Knight:
    #BLACK OR WHITE
    #HAVE DIFFERENT MOVES FOR ALL POSSIBLE 8

class Bishop:
    #BLACK OR WHITE
    #ALL MOVES (NUMBER OF SQUARES IN DIRECTION)

class Rook:
    #BLACK OR WHITE
    #ALL MOVES (NUMBER OF SQUARES IN DIRECTION)

class King:
    #BLACK OR WHITE
    #CHECK, CHECKMATE
    #ALL 8 MOVES
    
class Queen:
    #BLACK OR WHITE
    #ALL MOVES NUMBER OF SQUARES IN DIRECTION)